import localFont from "next/font/local";
import "./globals.css";
import { Barlow_Condensed } from "next/font/google";

const barlow_Condensed = Barlow_Condensed({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});


export const metadata = {
   title: "Burger | A healty Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={barlow_Condensed.className}
      >
        {children}
      </body>
    </html>
  );
}
